image: docker:latest

services:
- docker:dind

before_script:
- docker info

build_images:
  tags:
    - docker
  stage: build
  script:
    - for im in labrobotica gitlabci django-ci openldap;do cd ${im}; docker build -t ${im} .; cd ..; done
