image: docker:1.10

services:
- docker:1.10-dind

before_script:
- docker info

labrobotica:
  stage: build
  script:
  - cd labrobotica
  - docker build -t labrobotica .

gitlabci:
  stage: build
  script:
  - cd gitlabci
  - docker build -t gitlabci .
